# Generated by Django 3.1.3 on 2020-11-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='date',
            field=models.DateField(null=True, verbose_name='Post date'),
        ),
    ]
